spring.application.name=fitness-service


server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/fitnessdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (must be same as User Service)
jwt.secret=your-secret-key-at-least-32-characters-long
jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html